import FeaturedArt from "../components/FeaturedArt";

export default function Home() {
  return (
    <section className="pt-32 px-6 text-center">
      <h1 className="text-6xl font-bold mb-4 bg-gradient-to-r from-brand to-pink-500 bg-clip-text text-transparent">
        Create Stunning AI Art
      </h1>
      <p className="opacity-80 max-w-2xl mx-auto">
        Explore art generated by AI — purchase prompts + workflows, build inspiration.
      </p>

      <FeaturedArt />
    </section>
  );
}